import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./../components/NavBar/index";
import Cards from "../components/Cards";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <Navbar />
        <title>Devex Solucoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 gap-6">
          <div className="rounded overflow-hidden shadow-lg">
            <Cards />
          </div>
          <div className="rounded overflow-hidden shadow-lg">
            <Cards />
          </div>
          <div className="rounded overflow-hidden shadow-lg">
            <Cards />
          </div>
          <div className="rounded overflow-hidden shadow-lg">
            <Cards />
          </div>
        </div>
      </main>
    </div>
  );
}
