import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from './../components/NavBar/index';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <Navbar/>
        <title>Devex Solucoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </Head>
    </div>
  );
}
